
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Access-Control-Allow-Origin = "*"

[build]
  command = "vite build && node scripts/generateSitemap.js"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NETLIFY_EXPERIMENTAL_FEATURES_OPT_IN = "prerender"

[build.processing]
  skip_processing = false
  
[build.processing.html]
  pretty_urls = true

# Enable form detection specifically
[functions]
  directory = "netlify/functions"
  
[dev]
  command = "vite"
  
# Form success redirects
[[redirects]]
  from = "/thank-you"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/*"
  function = "transform"
