// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykcgooinlzlhtonueasz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrY2dvb2lubHpsaHRvbnVlYXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyODg4MjMsImV4cCI6MjA1NDg2NDgyM30.IthQpwAUGv_Ku5lOf6g9YyUqlm-xDCdweLY1U3AVJaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);